
export const FETCH_FURNITURE_REQUESTED = 'FETCH_FURNITURE_REQUESTED';
export const FETCH_FURNITURE_SUCCESS = 'FETCH_FURNITURE_SUCCESS';
export const FETCH_FURNITURE_FAILURE= 'FETCH_FURNITURE_FAILURE';

export const FURNITURE_ADDED_TO_CART = 'FURNITURE_ADDED_TO_CART';
export const FURNITURE_REMOVED_FROM_CART = 'FURNITURE_REMOVED_FROM_CART';
export const FURNITURE_DELETED_FROM_CART = 'FURNITURE_DELETED_FROM_CART';